### PR TITLE
Fix the problem that could not proceed or break the pipeline created by others

### LINKED ISSUE #407: Can not proceed or break the pipeline created by others
**Versions used**
KubeSphere: `v3.2.1-rc.2`

How To Reproduce

1、Create pipeline use the following Jenkinsfile with account 'A'
```
pipeline {
    agent any
    stages {
        stage('Example') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                }
            }
            steps {
                echo "Hello, ${PERSON}, nice to meet you."
            }
        }
    }
}

```
2、Run the pipeline created in step 1 with account 'admin'
3、Proceed or break the pipeline in 'Record details' page

**Actual behavior**

user admin can not  proceed or break the pipeline

https://user-images.githubusercontent.com/68640256/145140855-77c59d94-2787-44d4-abb8-f3d92cb2df6b.mov

/kind bug
/cc @kubesphere/sig-devops 
/priority high

### PR DESCRIPTION
**Pull request by JohnNiang**
### What this PR dose

Refine approvable check logic, which `approvableCheck` requires the users who have PipelineRun management permission to approve a PipelineRun. If the particular submitters exist, we also restrict the users who are in the particular submitters.

### Why we need it

Since v3.2.0, ks-devops was separated from KubeSphere, which led to a problem that ks-devops could not obtain permissions for currently logging in user, so that we would not determine whether the user has sufficient permission to approve a PipelineRun. So we changed the approvable check logic to adapt the problem.

Please note that our APIs are protected by `ks-apiserver` based on RBAC.

### Which issue this PR fix

Fixes #407 

### Steps to test

Docker image for test:

```bash
johnniang/devops-apiserver:dev-v3.2.1-rc.3-ec505c7
```

1. Create a Workspace, DevOps Project
2. Create two roles for the DevOps Project with permissions Pipeline management only and Pipeline viewing only respectively
3. Create two accounts (e.g.: tester-a and tester-b) and assign two roles to them respectively
4. Create a Pipeline via admin account with Jenkinsfile as below:
    ```groovy
    pipeline {
        agent none
        stages {
            stage('Example') {
                input {
                    message "Should we continue?"
                    ok "Yes, we should."
                    submitter ""
                    parameters {
                        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                    }
                }
                steps {
                    echo "Hello, ${PERSON}, nice to meet you."
                }
            }
        }
    }
    ```
1. Run the Pipeline multi times using admin account
2. Try to approve the Pipeline with three account
3. Change the submitter and try again

/kind bug
/cc @kubesphere/sig-devops 
/milestone v3.2

### CODE REVIEW

File: pkg/kapis/devops/v1alpha2/devops.go [hunk 1]
```diff
@@ -318,65 +317,36 @@ func (h *ProjectPipelineHandler) GetPipelineRunNodes(req *restful.Request, resp
...
 				continue
 			}
-
-			nodes[i].Steps[j].Approvable = isAdmin || createdByCurrentUser || step.Input.Approvable(userInfo.GetName())
+			if len(step.Input.GetSubmitters()) == 0 {
+				// TODO: no particular submitters, we make the PipelineRun approvable by default.
+				// Until we can obtain the permissions of the currently logged in user
+				step.Approvable = true
+			} else {
+				step.Approvable = step.Input.Approvable(userInfo.GetName())
```
Comment (LinuxSuRen) [inline pkg/kapis/devops/v1alpha2/devops.go:348]: What happens if there is a user A who is the owner of this Pipeline, and A is not a submitter. In this case, A will not be able to approve or reject it.

IMO, it is weird.

File: pkg/kapis/devops/v1alpha2/devops.go [hunk 2]
```diff
@@ -440,6 +410,9 @@ func (h *ProjectPipelineHandler) hasSubmitPermission(req *restful.Request) (hasP
 		err = errors.New("cannot get the submitters of current pipeline run")
 		return
 	}
+	if !hasPermit && err == nil {
+		err = fmt.Errorf("you have no permission to approve this pipeline run")
```
Comment (LinuxSuRen) [inline pkg/kapis/devops/v1alpha2/devops.go:414]: `pipeline run` or `pipelinerun`, or `pipeline run record`

We don't have a expression `pipeline run`

**Review by LinuxSuRen — CHANGES_REQUESTED** [review]

**Comment by JohnNiang** [comment]
Hi @LinuxSuRen , I have done according your suggestions.

**Review by LinuxSuRen — COMMENTED** [review]
/lgtm

**Comment by LinuxSuRen** [comment]
Please confirm if this PR should be cherry-pick into release-3.2
