### PR TITLE
Fix the multi-branch PipelineRun cannot be deleted

### LINKED ISSUE #417: Unable to delete Jenkins build while PipelineRun was deleted
### What happened

When we try to delete a PipelineRun, the build in Jenkins won't be deleted. And something wrong happens:

Log details in `devops-controller`:
```go
E1222 06:23:58.829460       1 pipelinerun_controller.go:71] pipelinerun-controller "msg"="unable to fetch PipelineRun" "error"="PipelineRun.devops.kubesphere.io \"multi-branch-test-f7mwq\" not found" "PipelineRun"={"Namespace":"my-devops-projectdq8jj","Name":"multi-branch-test-f7mwq"} 
```

### Steps to reproduce

1. Create a Pipeline and run it
1. Delete a PipelineRun  
    ```bash
    kubectl -n $NAMESPACE delete pipelineruns.devops.kubesphere.io $PIPELINE_RUN
    ```
1. See the build in Jenkins dashboard

/kind bug

### PR DESCRIPTION
**Pull request by LinuxSuRen**
### What type of PR is this?

/kind bug

### What this PR does / why we need it:
As I mentioned in the PR title.

### Which issue(s) this PR fixes:

Fixes #417

### Special notes for reviewers:

If you want to help to test with the temporary image, please try this one
```
surenpi/devops-controller:dev-v3.2.1-d2faf87@sha256:5d2a8c661d06c911f729dd8f6b87f8463a164a8fbbd191aba2f8b11605e75883
```

### Does this PR introduce a user-facing change??

```release-note
Fix the multi-branch PipelineRun cannot be deleted
```

### CODE REVIEW

File: controllers/jenkins/pipelinerun/jenkins_handler_test.go [hunk 1]
```diff
@@ -220,3 +221,77 @@ var _ = Describe("Test deleteJenkinsJobHistory", func() {
...
+		name: "a multi-branch PipelineRun",
+		args: args{
+			pipelineRun: &v1alpha3.PipelineRun{
+				ObjectMeta: v1.ObjectMeta{
+					Namespace: "ns",
+					Name:      "run",
+				},
+				Spec: v1alpha3.PipelineRunSpec{
+					SCM: &v1alpha3.SCM{
+						RefName: "master",
```
Comment (JohnNiang) [inline controllers/jenkins/pipelinerun/jenkins_handler_test.go:282]: It would be better if you test non-ascii branch name and name with special characters as well. Like `主分支` and `feat/feature-a`.

Comment (LinuxSuRen) [reply controllers/jenkins/pipelinerun/jenkins_handler_test.go:282]: Good point. But it works well. And it looks like we don't need to handle it in this function.

image

Comment (JohnNiang) [reply controllers/jenkins/pipelinerun/jenkins_handler_test.go:282]: I found that the spec.scm.refName has been encoded before setting. So there is no problem with non-ascii branch name and name with special characters.

**Review by JohnNiang — APPROVED** [review]
/lgtm
