### PR TITLE
Fix the problem of rendering choice parameter incorrectly

### LINKED ISSUE #365: Choice parameter is not rendered correctly
### What happened?

`Build Parameters` setting was as follows:
image

But when I ran the Pipeline, I got an `input` instead of `select`:

image

### Expected behaviour

image

**Note:** I'm not sure whether this issue is caused by frontend or backend, so I submit this issue at here currently.

> https://kubesphere.com.cn/forum/d/6126-v32-devops-choice [In Chinese]

/kind bug
/priority high

### PR DESCRIPTION
**Pull request by JohnNiang**
### What this PR dose

1. Bump Jenkins client;
2. Simplify type of parameter definition.

### Why we need it

Please see #365 

### Which issue this PR fixes

Fix #365 

### How to test

Docker image for test: `johnniang/devops-controller:dev-v3.2.0-4fce6cf`

### Special notes for reviewers

Upstream PR: 

- https://github.com/jenkins-zh/jenkins-client/pull/39

/kind bug

### CODE REVIEW

File: controllers/jenkins/pipeline/metadata_converter.go [hunk 1]
```diff
@@ -27,6 +27,28 @@ func convertPipeline(jobPipeline *job.Pipeline) *pipeline.Metadata {
...
 }
 
+// ParameterDefinitionTypeMap is for simplifying parameter definition type.
+var ParameterDefinitionTypeMap = map[string]string{
+	"StringParameterDefinition":   "string",
+	"ChoiceParameterDefinition":   "choice",
+	"TextParameterDefinition":     "text",
+	"BooleanParameterDefinition":  "boolean",
+	"FileParameterDefinition":     "file",
+	"PasswordParameterDefinition": "password",
```
Comment (LinuxSuRen) [inline controllers/jenkins/pipeline/metadata_converter.go:37]: we already have this map. Please consider reusing it.

https://github.com/kubesphere/ks-devops/blob/4904f4ebbc3f88ae77402658f3e4e23e479f8b49/pkg/client/devops/jenkins/constants.go#L44

**Review by LinuxSuRen — CHANGES_REQUESTED** [review]

**Review by LinuxSuRen — COMMENTED** [review]
/label tide/merge-method-squash
/approve
/lgtm

File: controllers/jenkins/pipeline/metadata_converter.go (hunk 1 above)
Comment (JohnNiang) [reply controllers/jenkins/pipeline/metadata_converter.go]: Those map data cannot be merged into 

https://github.com/kubesphere/ks-devops/blob/4904f4ebbc3f88ae77402658f3e4e23e479f8b49/pkg/client/devops/jenkins/constants.go#L38-L45

This behaviour would break logic as below

https://github.com/kubesphere/ks-devops/blob/4904f4ebbc3f88ae77402658f3e4e23e479f8b49/pkg/client/devops/jenkins/pipeline_internal.go#L184-L185

Comment (JohnNiang) [reply controllers/jenkins/pipeline/metadata_converter.go]: And [the test error](https://github.com/kubesphere/ks-devops/runs/4307589828?check_suite_focus=true) was caused by the merging.

Comment (LinuxSuRen) [reply controllers/jenkins/pipeline/metadata_converter.go]: I didn't request you to merge them together. Please consider to reuse them.

Comment (JohnNiang) [reply controllers/jenkins/pipeline/metadata_converter.go]: Got it.

**Review by LinuxSuRen — COMMENTED** [review]
/lgtm

**Comment by LinuxSuRen** [comment]
The related issue is https://github.com/kubesphere/ks-devops/issues/537
